const express=require('express')
const route=express.Router()

const checkid=require('./../middlewares/checkmongodbobject')
const validator = require('./../middlewares/validator')
const isadmin=require('./../middlewares/isadmin')
const addcourse=require('./../controllers/addcourse')
const showusers=require('./../controllers/showusers')
const courseupload=require('./../config/courseuploads')
const adduser=require('./../controllers/adduser')
const loginreport=require('./../controllers/loginreport')
const fourteenreport=require('./../controllers/14daysreport')
const sellsreport=require('./../controllers/sellsreport')
const deleteacount=require('./../controllers/deleteacount')
const deletecomment=require('./../controllers/deletecomment')
const replycomment=require('./../controllers/replycomment')
const courseenrollments=require('./../controllers/coursesenrollments')
const incompleteenrollment=require('./../controllers/getincompleteenrollment')
const confirmenrollment=require('./../controllers/confirmenrollment')
const usercount=require('./../controllers/getusercount')
const coursecount=require('./../controllers/getcoursecount')
const getuserforadmin=require('./../controllers/getuserforadmin')
const finduserbyphone=require('./../controllers/getuserbyphone')
const addusercourse=require('./../controllers/addusercourse')
const adduserval=require('./../validators/adduseradmin')
const edituserval=require('./../validators/edituseradmin')
const unban=require('./../controllers/unban')

route.post('/addcourse/:courseid?',isadmin,checkid('courseid'),courseupload.fields([
{name:'thumbnail',maxCount:1},
{name:'introvideo',maxCount:1}
]),addcourse)
route.post('/adduser/:userid',isadmin,checkid('userid'),edituserval,validator,adduser)
route.post('/adduser',isadmin,adduserval,validator,adduser)
route.post('/deleteuser/:id',isadmin,checkid('id'),deleteacount)
route.post('/unban/:id',isadmin,checkid('id'),unban)
route.post('/replycomment/:id',isadmin,checkid('id'),replycomment)
route.post('/deletecomment/:id',isadmin,checkid('id'),deletecomment)
route.post('/confirmenrollment/:enrollmentid',isadmin,checkid('enrollmentid'),confirmenrollment)
route.post('/courses/addusertocourse/:courseId/:userId',isadmin,checkid('courseId'),checkid('userId'),addusercourse)
route.get('/courseenrollments/:courseid',isadmin,checkid('courseid'),courseenrollments)
route.get('/getusers',isadmin,showusers)
route.get('/loginreports',isadmin,loginreport)
route.get('/14daysreport',isadmin,fourteenreport)
route.get('/sellsreport',isadmin,sellsreport)
route.get('/getincompleteenrollment',isadmin,incompleteenrollment)
route.get('/userscount',isadmin,usercount)
route.get('/coursescount',isadmin,coursecount)
route.get('/getuser/:userid',checkid('userid'),isadmin,getuserforadmin)
route.get('/finduserbyphone/:phone',isadmin,finduserbyphone)

module.exports=route
